<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.usCa76w' shared service.

return $this->privates['.service_locator.usCa76w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'catrepo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'prodrepo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService.php', true],
    'tagrepo' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService.php', true],
]);
