<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.khjqE1f' shared service.

return $this->privates['.service_locator.khjqE1f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'accrepo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService.php', true],
]);
