<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\CartService' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/CartService.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-core/Security.php';

return $this->privates['App\Services\CartService'] = new \App\Services\CartService(($this->services['session'] ?? $this->load('getSessionService.php')), ($this->privates['App\Repository\OrdersRepository'] ?? $this->load('getOrdersRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), new \Symfony\Component\Security\Core\Security(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
])));
