<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8HfssOZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8HfssOZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8HfssOZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8HfssOZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8HfssOZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8HfssOZ',
    'container.build_id' => '57eb3e62',
    'container.build_time' => 1555676448,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8HfssOZ');
