<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYHLPRN9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYHLPRN9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYHLPRN9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYHLPRN9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYHLPRN9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YHLPRN9',
    'container.build_id' => '9017bd44',
    'container.build_time' => 1555671057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYHLPRN9');
