<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAb9xPXs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAb9xPXs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAb9xPXs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAb9xPXs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAb9xPXs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ab9xPXs',
    'container.build_id' => 'a7d52ba3',
    'container.build_time' => 1555664732,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAb9xPXs');
